### PR TITLE
Automatically store contract code of the DAO on factory initialization

### LINKED ISSUE #91: Primary README causes error(s)
There is a comment about this in Telegram that I could not reproduce, but when I tried following the directions on my Macbook I ran into this error. See Step 6 of the README at the project root

```bash
near call $CONTRACT_ID create "{\"name\": \"genesis\", \"args\": \"$ARGS\"}" --accountId $CONTRACT_ID --amount 5 --gas 150000000000000
```

```bash
Scheduling a call: sputfact.mike.testnet.create({"name": "genesis", "args": "eyJjb25maWciOiB7Im5hbWUiOiAiZ2VuZXNpcyIsICJwdXJwb3NlIjogIkdlbmVzaXMgREFPIiwgIm1ldGFkYXRhIjoiIn0sICJwb2xpY3kiOiBbImNvdW5jaWwtbWVtYmVyLnRlc3RuZXQiLCAiWU9VUl9BQ0NPVU5ULnRlc3RuZXQiXX0K"}) with attached 5 NEAR
Doing account.functionCall()
Receipts: 8pzTSgQNivDtTe27pdnNf3vovrpUPvfWGC7dpJKPNkWF, 5aVK9Uazj5HsMbRNYmrG32ESQFxFycmtj9cZ3P7QNVaz
	Failure [sputfact.mike.testnet]: Error: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'Must have code hash', sputnikdao-factory2/src/lib.rs:123:64"}}
ServerTransactionError: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'Must have code hash', sputnikdao-factory2/src/lib.rs:123:64"}}
    at Object.parseResultError (/Users/mike/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/Users/mike/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:160:36)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async scheduleFunctionCall (/Users/mike/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/Users/mike/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'FunctionCallError',
  context: undefined,
  index: 0,
  kind: {
    ExecutionError: "Smart contract panicked: panicked at 'Must have code hash', sputnikdao-factory2/src/lib.rs:123:64"
  },
```

I think it's this line:
https://github.com/near-daos/sputnik-dao-contract/blame/90184759ff1fd18212a4cfa638a7a950ba4177e9/sputnikdao-factory2/src/lib.rs#L59

### PR DESCRIPTION
**Pull request by ctindogaru**
Fixes #91

### CODE REVIEW

**Comment by ctindogaru** [comment]
Must merge https://github.com/near-daos/sputnik-dao-contract/pull/92 first

File: sputnikdao-factory2/src/lib.rs [hunk 1]
```diff
@@ -22,10 +24,19 @@ pub struct SputnikDAOFactory {
...
+        let this = Self {
             factory_manager: FactoryManager {},
             daos: UnorderedSet::new(b"d".to_vec()),
-        }
+        };
+        this.internal_store_initial_version();
+        this
+    }
+
+    pub fn internal_store_initial_version(&self) {
```
Comment (mikedotexe) [inline sputnikdao-factory2/src/lib.rs:35]: 🙏🏼

File: sputnikdao-factory2/src/lib.rs [hunk 2]
```diff
@@ -162,30 +173,18 @@ pub extern "C" fn store() {
...
     #[test]
     fn test_basics() {
         let mut context = VMContextBuilder::new();
-        testing_env!(context.current_account_id(accounts(0)).build());
+        testing_env!(context
+            .current_account_id(accounts(0))
+            .predecessor_account_id(accounts(0))
+            .build());
         let mut factory = SputnikDAOFactory::new();
-        let hash = add_contract(&mut context.build(), &mut factory);
```
Comment (mikedotexe) [inline sputnikdao-factory2/src/lib.rs:186]: Seems like we should eventually write Sandbox tests for this, as I imagine unit tests aren't nearly powerful enough to test updates
